### ISSUE TITLE
panic: routing: not found，以及其他错误

### ISSUE THREAD

**Issue by x1ntt** [chenjia404/p2ptunnel#3]
被链接端没什么问题，一下所有问题都是连接端的

+ 每次连接稳定出现这个问题，连接目标是一个arm架构的小机箱
一开始会提示
```Shell
2022/10/09 14:37:17 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```
修改缓冲区之后就好了，下面是连接端的报错，每次一定会出现
```Shell
C:\Users\Administrator\Downloads\p2ptunnel_v0.0.3_windows_amd64>p2ptunnel.exe -id 12D3KooWPn16YRgB1gb1dNvv4TSbjCzF6faHA61wCiDE9Ka7CBcu -ip 127.0.0.3
p2ptunnel 0.0.3-"e7affef"
buildTime "2022-10-08T13:42:23Z"
System version: amd64/windows
Golang version: go1.19.2
2022/10/09 14:59:02 Connect id:%s ip:%s 12D3KooWPn16YRgB1gb1dNvv4TSbjCzF6faHA61wCiDE9Ka7CBcu 127.0.0.3
2022/10/09 14:59:13 routing: not found
panic: routing: not found


goroutine 1 [running]:
log.Panicln({0xc0034dff10?, 0xc00013e080?, 0x34?})
        C:/soft/Go/src/log/log.go:402 +0x65
main.main()
        C:/github/p2ptunnel/main.go:67 +0x511
```
## 以下被链接端是我的笔记本电脑win11
+ 连接端需要重复连接，几个错误大约随机出现
```Shell
=================第一种
2022/10/09 14:39:47 Write on stream 4 canceled with error code 0
panic: Write on stream 4 canceled with error code 0


goroutine 1 [running]:
log.Panicln({0xc00398bf10?, 0xc000036300?, 0x34?})
        C:/soft/Go/src/log/log.go:402 +0x65
main.main()
        C:/github/p2ptunnel/main.go:67 +0x511

=================第二种
Golang version: go1.19.2
2022-10-09T14:38:50.971+0800    [31mERROR[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}
2022-10-09T14:38:50.988+0800    [31mERROR[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}
2022/10/09 14:38:52 Connect id:%s ip:%s 12D3KooWS5QHB8YdMhh67inh5XtHiVfgdXG9ELfyNgWToMYfZrEA 127.0.0.5
2022/10/09 14:39:07 Write on stream 4 canceled with error code 0
panic: Write on stream 4 canceled with error code 0


goroutine 1 [running]:
log.Panicln({0xc00365ff10?, 0xc000036300?, 0x34?})
        C:/soft/Go/src/log/log.go:402 +0x65
main.main()
        C:/github/p2ptunnel/main.go:67 +0x511

================第三种
Golang version: go1.19.2
2022-10-09T14:38:03.460+0800    [31mERROR[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}
2022-10-09T14:38:07.601+0800    [31mERROR[0m  autorelay       autorelay/autorelay.go:80       failed to start relay finder    {"error": "relayFinder already running"}
2022/10/09 14:38:08 Connect id:%s ip:%s 12D3KooWS5QHB8YdMhh67inh5XtHiVfgdXG9ELfyNgWToMYfZrEA 127.0.0.5
2022/10/09 14:38:23 Application error 0x0: conn-17439: system: cannot reserve inbound connection: resource limit exceeded
panic: Application error 0x0: conn-17439: system: cannot reserve inbound connection: resource limit exceeded


goroutine 1 [running]:
log.Panicln({0xc002951f10?, 0xc000036300?, 0x34?})
        C:/soft/Go/src/log/log.go:402 +0x65
main.main()
        C:/github/p2ptunnel/main.go:67 +0x511
```

+ 连接成功之后再断开，需要重启被连接端一次才能再次连接上，否则不管重试几次都不行 
+ 首次连接重试了三次，之后每次重启被连接端就会很快连接上

此外，是否可以编译一个mips版本，我想放到路由器上面。如果可以的话，支持一个隧道转发多个端口是否可以呢？这样就很适合在路由器上面跑了。
我不会go，如果上面的操作比较麻烦的话，给出编译过程也可以

感谢~~

**Comment by chenjia404** [comment]
routing: not found是没有找到目标节点，建议目标节点先连接上去1-2分钟，这个节点发现依赖公网。

第三个错误是资源使用限制的错误，我这边修改一下上限，其它几个错误，我追踪一下。

mips版本
[p2ptunnel_v0.0.3_Linux_mipsle_hardfloat.tar.gz](https://github.com/chenjia404/p2ptunnel/files/9742009/p2ptunnel_v0.0.3_Linux_mipsle_hardfloat.tar.gz)

**Comment by x1ntt** [comment]
> 

感谢~~ 如果需要复现请联系我

**Comment by x1ntt** [comment]
+ mips 版本在我的路由器上面运行什么输出也没有，就那么一直阻塞
+ 在我的arm主机上能获取到id，但是连接端连接不上他 提示`routin: not found` 等多久都不行 这是和网络环境有关吗 可是他们有相同的网络环境
@chenjia404

**Comment by chenjia404** [comment]
routin: not found是节点没有寻找到，我发布了一个0.0.4版本，加强了节点广播能力。

**Comment by x1ntt** [comment]
感谢~ 
@chenjia404 然后还有一个问题，就是我连接上一次之后，再断开。那么在重启被连接端之前，连接端就连接不上了。

**Comment by chenjia404** [comment]
如果是tcp，试试这个版本呢，稳定很多 https://github.com/chenjia404/go-p2ptunnel

**Comment by x1ntt** [comment]
> 

好 稍后看看 感谢
